export const DEFAULT_GAMEPLAY_TUNING = {
    drive: {
        maxSpeed: 30,
        acceleration: 11,
        friction: 4.5,
        brakeStrength: 3.5,
        throttleDragReduction: 0.25,
        overRotationSpeedPenalty: 7,
        overRotationAngleOffset: 8,
    },

    pitch: {
        liftTorque: 360,
        forwardLiftTorque: 320,
        settleTorque: 280,
        forwardSettleTorque: 240,
        gravityTorque: 160,
        angularDamping: 1,
        maxAngle: 60,
        forwardMaxAngle: 52,
        validMinAngle: 12,
        stoppieMinAngle: 10,
        validMaxMargin: 4,
    },

    riderControl: {
        throttleLiftBase: 1.18,
        leanBackLiftBonus: 1.05,
        speedLiftFactor: 24,
        leanBackDirectLift: 26,
        launchAssistTorque: 220,
        launchAssistMaxAngle: 14,
        brakeLiftBase: 1.05,
        forwardWeightLiftBonus: 1.1,
        brakeLiftMinSpeedRatio: 0.08,
        brakeSpeedLiftFactor: 26,
        forwardWeightDirectLift: 22,
        brakeLaunchAssistTorque: 200,
        brakeLaunchAssistMaxAngle: 10,
        brakeSettleBase: 0.78,
        leanForwardSettleFactor: 0.92,
        settleBaseRate: 0.5,
        settleControlScale: 0.7,
        settleAngleRecovery: 0.45,
        throttleStoppieRecoveryBase: 0.9,
        backWeightStoppieRecoveryBonus: 0.85,
        stoppieRecoveryBaseRate: 0.45,
        stoppieRecoveryControlScale: 0.7,
        stoppieRecoveryAngleScale: 0.5,
        passiveDropSpeedFactor: 16,
        passiveDropAngleRecovery: 32,
        releaseDropBoost: 160,
        forwardReleaseRecoveryBoost: 135,
        controlDeadZone: 0.001,
    },

    balance: {
        driftBase: 12,
        driftSpeedFactor: 20,
        driftWaveFreq1: 0.65,
        driftWaveFreq2: 2.4,
        driftWaveAmp2: 0.45,
        driftInfluence: 0.28,
        roadKickFreq: 3.6,
        roadKickInfluence: 0.5,
        minSpeedForDrift: 0.8,
        wheelieChaosBase: 12,
        wheelieChaosBuildRate: 16,
        wheelieChaosCap: 34,
        perfectChaosBonus: 10,
        wheelieChaosFreq1: 7.5,
        wheelieChaosFreq2: 12.5,
        wheelieChaosMix: 0.45,
        backFallStartAngle: 34,
        backFallTorque: 46,
        backFallSpeedFactor: 28,
        backFallChaos: 18,
        frontDriftBase: 8,
        frontDriftSpeedFactor: 12,
        frontDriftWaveFreq1: 1.2,
        frontDriftWaveFreq2: 4.5,
        frontDriftWaveMix: 0.35,
        frontDriftInfluence: 0.18,
        frontFallStartAngle: 20,
        frontFallTorque: 60,
        frontFallSpeedFactor: 38,
        frontFallChaos: 18,
    },

    scoring: {
        perfectAngle: 31,
        perfectWindow: 6,
        perfectMultiplier: 2.4,
        baseScoreRate: 0.5,
        angleScoreDivisor: 38,
        minSpeedForValid: 2,
    },

    world: {
        roadLength: 300,
        roadWidth: 8,
    },

    visuals: {
        bobFrequency: 0,
        bobAmplitude: 0.02,
        wheelSpinRate: 3.2,
    },

    arcade: {
        laneCount: 3,
        laneWidth: 2.2,
        laneSwitchSpeed: 8,
        coinSpacing: 12,
        coinValue: 10,
        coinPickupRadius: 1.8,
        obstacleSpacing: 25,
        obstacleHitRadius: 1.2,
        startGap: 20,
        distanceScoreRate: 0.5,
    },
}
